apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: go-yakilles-gitops
  description: This is GitOps manifest for go-yakilles   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=go-yakilles
    backstage.io/kubernetes-id: go-yakilles 
    backstage.io/techdocs-ref: dir:.
    dev.azure.com/project-repo: rhtap-qe-jsmid/go-yakilles-gitops
    dev.azure.com/project: shared-public
    dev.azure.com/build-definition: rhtap-qe-jsmid.go-yakilles-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:go-yakilles
