apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-yakilles
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-yakilles 
  name: go-yakilles
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-yakilles
    weight: 100 
